### ISSUE TITLE
Name for BC7 format

### ISSUE THREAD

**Issue by bangnoise** [Vidvox/hap#34]
Hap has supported BC7 textures for a while but never had a name for the format. We need one.

**Comment by leavittx** [comment]
How about simple Hap 7 ?

**Comment by bangnoise** [comment]
7 Doesn't make much sense as far as users are concerned - reads like a version number.

**Comment by leavittx** [comment]
Then I think it's gonna be Hap Q+

**Comment by leavittx** [comment]
@bangnoise 
What do you think?

**Comment by dlublin** [comment]
I think HAP Q+ doesn't work because it doesn't provided a clear path for how too handle future releases; we don't want to go to HAP Q++ from there. Our goal here is not just to name the new variation, but to also plan out a bit how we want to handle future naming to avoid confusion.

Quite frankly I am more concerned with actually making the new variation, we didn't come up with the original name "HAP" for the project until we were very far along in the development process.

If it would help to have an interim "codename" for the BC7 variation, my suggestion is HAP TNG (the next generation) for the time being.

**Comment by leavittx** [comment]
> I think HAP Q+ doesn't work because it doesn't provided a clear path for how too handle future releases; we don't want to go to HAP Q++ from there. Our goal here is not just to name the new variation, but to also plan out a bit how we want to handle future naming to avoid confusion.

Yeah, I'm also concerned about the possible "Hap Q+ Alpha" vs "Hap Q Alpha" confusion (people can easily mix them up)
 
> Quite frankly I am more concerned with actually making the new variation, we didn't come up with the original name "HAP" for the project until we were very far along in the development process.

I actually got a proof of concept BC7 version working here in my Demolition Media plugin for vvvv today (should also work in Unity without any problems)

My feeling is that the biggest work here would be to choose an optimal BC7 encoder in terms of speed/quality which we can incorporate into FFmpeg/AfterEffects/etc. There are plenty of them. Moreover there are 8 block encoding modes in BC7, and from what I've understood, one can combine them independently within a single texture depending on block content in order to provide the best possible image quality.
 
> If it would help to have an interim "codename" for the BC7 variation, my suggestion is HAP TNG (the next generation) for the time being.

TNG is a bit too long as for me. How about just HAP NG?
(And probably HAP HDR or HAP NG HDR for BC6 mode)

**Comment by bangnoise** [comment]
Please can we limit discussion in this issue to the final name for the BC7 format. No requests for feedback, no discussion about wider project goals.

**Comment by leavittx** [comment]
Have we agreed on something here?

**Comment by dlublin** [comment]
Hey Lev!

I sent you an email with further discussion, did it arrive?

**Comment by leavittx** [comment]
Yep, got the mail. Will get back to you soon with my thoughts

**Comment by leavittx** [comment]
Hi David. Have you recieved my mail?

**Comment by leavittx** [comment]
Anybody alive in this thread?

**Comment by mbechard** [comment]
Two options I can see working are either:
1. Being explicit with the naming. Hap BC7, Hap BC6U etc.

2a). Folding BC7 into Hap Q, since it's not a huge difference in quality/size, but more of an incremental improvement. It can be chosen on the encoder side using a "Quality" setting. That Quality setting and say BC7 if it wishes, but it's still Hap Q as the branding.
2b). BC6 would be 'Hap F' for floating point.

**Comment by bentoncbainbridge** [comment]
How about Hap G?

Benton C Bainbridge | +1.646.338.9172 <(646)%20338-9172>
Video paintings for *Howling: **Healing*
<https://youtu.be/PIVxn6i-Zuo>*, **Need
You Now* <https://youtu.be/oMcDjE79fVY>, *Bind
<https://youtu.be/1dNZQmgaLMc> & **Phases <https://youtu.be/IQh3Rdlz2YM>*

**Comment by bentoncbainbridge** [comment]
Or, Hap E!

Benton C Bainbridge | +1.646.338.9172 <(646)%20338-9172>
Video paintings for *Howling: **Healing*
<https://youtu.be/PIVxn6i-Zuo>*, **Need
You Now* <https://youtu.be/oMcDjE79fVY>, *Bind
<https://youtu.be/1dNZQmgaLMc> & **Phases <https://youtu.be/IQh3Rdlz2YM>*

**Comment by JonnyTech** [comment]
> Or, Hap E!

Happy :)

**Comment by bangnoise** [comment]
Using Hap Q for BC7 isn't a terrible idea - the only complication is that BC7 can carry alpha, and we currently differentiate between Hap Q and Hap Q Alpha. Would Hap Q Alpha make sense for all uses of BC7?

**Comment by bangnoise** [comment]
On further reflection, Hap Q Alpha has a higher bitrate than BC7, which would cause confusion. I think because of the potential for confusion around Hap Q's alpha-oriented naming, a new name is needed.

Although explicit naming (Hap BC7) has appeal to the technically-minded, I think it risks being unfriendly jargon for users.

I'd suggest a letter which can't run into "Hap" to make a new word - R (comes after Hap Q) or G or J would be my votes.

**Comment by mbechard** [comment]
BC7 can choose not to encode alpha and leaves more bits for RBG as far as I can tell. So the choice of one or the other would be telling the compressor what BC7 modes to use (Modes 0-3 only when choosing to ignore alpha). That would work for the Hap Q and Hap Q Alpha differences.

I can see the confusion about the bitrate though.

**Comment by bangnoise** [comment]
That's fine for encoders, but decoders need a name from the Hap7 FourCC - they wouldn't know whether to display Hap Q or Hap Q Alpha.

**Comment by mbechard** [comment]
Could that just be differentiated by a different FourCC that the encoder chooses based on what it's encode settings are? Not sure what the rules are for FourCC + English name mappings...

**Comment by bangnoise** [comment]
Hap7 is already a specified FourCC for any BC7, though we could deprecate it in favour of two new ones.

It would be adding two FourCCs to describe identical data, but it does signify an intention, and I appreciate that it can be a useful hint to an encoder to never consider alpha, and useful information for compositing that alpha should be ignored.

**Comment by mvji** [comment]
Hello,

I think using HAPQ and HAPQ Alpha as "human name" for another codec/fourcc, can confuse users.
It's seems better to me to choose another human name for BC7.

For the RGB/RGBA issue, 
Maybe we can consider to use only one fourcc code, for RGB and RGBA

And if the entire file doesn't need alpha, set the bitdepth at the container level (24 instead of 32)
Or use a frame information in order to indicate if alpha is used or not (adding a section, or use another value in the top level section (for RGB BC7).

The current value set in the documentation for BC7, can be in that case use for the RGBA case.

Martin

**Comment by bangnoise** [comment]
OK - in summary

- Hap7 remains the only four-cc for BC7 in Hap.
- Hap is a frame format and we try to limit conditions placed on containers, but we would expect encoders with knowledge about the presence of alpha to mark that in the container where the container supports it. Encoders are of course welcome to have a setting to ignore alpha (and they may well want to, to speed up encoding).
- a final suggestion for a human-readable name for this is incoming shortly...

**Comment by bangnoise** [comment]
Hap R

3a50947

thanks all
